- openid-sse-framework-1_0.html
- openid-sse-framework-1_0.txt
- openid-sse-framework-1_0.xml
It's a default encoding for JSON. Furthermore, the specification tells us
> A successful response MUST use the 200 OK HTTP status code and return a JSON object using the "application/json" content.
> It's unnecessary to specify the character as UTF-8 in all examples

- openid-sharedsignals-framework-1_0.html
- openid-sharedsignals-framework-1_0.md
- openid-sharedsignals-framework-1_0.txt
- replace all references to `https://schemas.openid.net/secevent/risc/delivery-method/push` with `urn:ietf:rfc:8935`
- replace all references to `https://schemas.openid.net/secevent/risc/delivery-method/poll` with `urn:ietf:rfc:8936`
> #28 update delivery method references to URNs

- openid-sharedsignals-framework-1_0.html
- openid-sharedsignals-framework-1_0.md
- openid-sharedsignals-framework-1_0.txt
Closes #36 (previous commits incorrectly refer to #45)
> Poll transmitter specified url

- openid-sharedsignals-framework-1_0.html
- openid-sharedsignals-framework-1_0.md
- openid-sharedsignals-framework-1_0.txt
As discussed in our most recent call, this PR adds an OPTIONAL "reason" to the response from a GET /status request.
The other work of removing subjects from the /status endpoint will come in a later PR because I suspect it may be more contentious.
> Add reason to GET /status response

- openid-sharedsignals-framework-1_0.html
- openid-sharedsignals-framework-1_0.md
- openid-sharedsignals-framework-1_0.txt
As discussed in last week's call, this PR removes subjects from the stream status concept. You can now only pause, disable, and enable an entire stream, rather than specific subjects within a stream.
This incidentally closes #56
> Remove subject from stream status

- openid-sharedsignals-framework-1_0.md
As per the discussions from issue #95 and specifically [this](https://github.com/openid/sharedsignals/issues/95#issuecomment-1677818418) comment. 
Proposing the changes to decouple SSF spec from OAuth 2 scopes/discovery
- Revert changes from https://github.com/openid/sharedsignals/pull/83
- References to [protected resource metadata](https://datatracker.ietf.org/doc/html/draft-jones-oauth-resource-metadata-04#name-protected-resource-metadata)
> Decouple SSF spec from OAuth2 scopes

- openid-caep-interoperability-profile-1_0.md
Verification events MUST include an opaque sub_id. Since Transmitters MUST send verification events, then Receivers MUST be prepared to accept them.
> Add opaque to the required subject formats

- openid-sharedsignals-framework-1_0.md
The spec contains multiple instances of phrases like "a SSF Event", "a SSF receiver", etc. These should be "an SSF ..." - other places in the specs already use the correct form.
See also, e.g., https://www.merriam-webster.com/grammar/is-it-a-or-an and https://blog.apastyle.org/apastyle/2012/04/using-a-or-an-with-acronyms-and-abbreviations.html
> Fix Indefinite Articles Before "SSF"

- openid-sharedsignals-framework-1_0.md
> Typographical Fixes

- openid-sharedsignals-framework-1_0.md
Addresses Issue #141 . When we added `description` to the Stream Configuration we said that it was an optional field. That left open a question about whether the other fields were required or not. The descriptions on the fields make it clear that some of them should be optional. This PR makes it explicit which ones are optional and which are required.
> Add OPTIONAL/REQUIRED to the fields in the stream configuration

- openid-sharedsignals-framework-1_0.md
This PR addressed issue #135 by adding `stream_id` to the response of a GET request for stream status. The response for a POST request already includes `stream_id` and it makes implementations easier if the GET and POST requests return the same object.
> Add stream_id to the response when getting stream status

- openid-sharedsignals-framework-1_0.md
Finishes the work for Issue #37 by updating the remaining examples that were incorrect.
The following examples all needed `subject` removed from the event, `sub_id` added to the base SET, or both:
- subject-ids-ex-simple
- subject-ids-ex-complex
- subject-properties-ex
- subject-custom-type-ex
- risc-event-subject-example
- caep-event-properties-example
- figarrayaud
In addition, `caep-event-properties-example` did not actually have a valid CAEP event body, so I updated that as well.
> Update subject/sub_id in examples. Fix CAEP example

- openid-sharedsignals-framework-1_0.md
This PR cleans up and clarifies the language around how a Transmitter MUST send Stream Updated events if it changes the status of a stream. It should address all concerns from issue #128
> Clarify language around sending Stream Updated events

- openid-sharedsignals-framework-1_0.md
There are three problems mentioned in Issue #166:
1) We need to add language that suggests the Receiver validate the Issuer value before doing discovery. This PR addresses that.
2) We need to add TLS restriction to the stream management endpoints. PR #173 addresses that.
3) We need to restrict delivery methods to only secure options. That is already done by the fact that the Stream Configuration metadata's `delivery.method` field can only be one of `push` or `poll`.
> Add sentence suggesting that Issuer information should be validated by the Receiver

- openid-sharedsignals-framework-1_0.md
`cause-time` is not a known field of the RISC `account-disabled` event. Removing it.
> Removed cause-time from RISC example

- openid-sharedsignals-framework-1_0.md
Fixes the language around an invalid state in the Verification event and requests that we add `invalid_state` to the IANA registry of SET error codes.
Please let me know if this seems like a reasonable format for the IANA request.
> Fix description of error code for invalid state

- openid-sharedsignals-framework-1_0.md
To address the attack identified in Issue #162, we recommend that the Receiver SHOULD check the `iss` value when getting a Stream Configuration from the Transmitter to ensure that it matches the Issuer that sent the Transmitter Configuration data.
> Add SHOULD language about checking the issuer value

- openid-caep-interoperability-profile-1_0.md
As discussed in WG meeting from 2024-05-14, specify that only one event is allowed in the interoperability profile.
Fixes Issue #167
> Specify one event per "events" claim of SET for Interoperability Profile

- openid-sharedsignals-framework-1_0.md
To address the attacks proposed in #161 and #160, this PR adda a paragraph indicating that all Stream Management API endpoints must use authorization that associates stream IDs with a specific Receiver, unless some other method of trust is established.
> Added language requiring authorization of stream management API

- .github/workflows/build-everything.yml
- openid-caep-interoperability-profile-1_0.md
We have defined the use of OAuth 2.0 as an authorization scheme in our interoperability draft. 
This PR adds more details about using OAuth constructs to make vendor interoperability more standardized.
> Include OAuth specifics in the interop spec

- openid-sharedsignals-framework-1_0.md
Added txn claims to examples and made a direct callout to the SET RFC and called out the explicit use of the claim.
> PR for Issue #157 (Update CAEP & RISC Events and SSF Docs with txn claim)

- openid-sharedsignals-framework-1_0.md
Addresses issue #163 by adding an optional field, `default_subjects` to the Transmitter Configuration data. The field is a string which can be either `ALL` or `NONE` and defaults to `NONE` if not provided. The interpretation of this field is as follows:
- `ALL`: All subjects are added by default. Calling `remove_subject_endpoint` acts like a filter, blocking the transmission of only the specified subjects. Calling `add_subject_endpoint` can effectively clear any filters set by `remove_subject_endpoint` but otherwise does nothing.
- `NONE`: No subjects are added by default. Calling `add_subject_endpoint` adds a subject to the stream. Calling `remove_subject_endpoint` can remove a previously added subject, but otherwise does nothing.
> Issue 163 - add field to configuration data indicating expected subject behavior for new streams

- openid-caep-1_0.md
On a Session Established event, `amr` is an optional claim whose value is an array of strings. However, the example includes a string instead.
This PR fixes the typo in the example.
> Fix CAEP Session Established event example

- openid-caep-interoperability-profile-1_0.md
We now recommend to follow [RFC9325](https://www.rfc-editor.org/rfc/rfc9325.html) instead of the obsolete [RFC7525](https://www.rfc-editor.org/rfc/rfc7525.html).
Fixes #212
> Update Network layer protection guidance in CAEP Interoperability Profile

- openid-caep-1_0.md
Continuning from https://github.com/openid/sharedsignals/pull/205 
(The original branch was messed up due to merge issues and limited github privileges)
New CAEP event - Risk level change event
Closes https://github.com/openid/sharedsignals/issues/200
Removed ips claim from the event and created https://github.com/openid/sharedsignals/issues/201 to handle it separately for all CAEP events.
> New CAEP event - Risk level change event

- README.md
- openid-caep-1_0.md
- openid-caep-interoperability-profile-1_0.md
- openid-sharedsignals-framework-1_0.md
There were a few links that used the old urls of the CAEP / SSF and some http links that should be https these days.
> Update out of date links

- openid-sharedsignals-framework-1_0.md
> Minor clarity edits

- openid-sharedsignals-framework-1_0.md
Fixes #149 
This PR should be non-normative (is it?!)  i've tried to better describe the default behavior when a transmitter does not support the defaulted stream delivery method.
> Clarify Stream Creation default delivery method behavior

- openid-sharedsignals-framework-1_0.md
Add text to section [7.1.1](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-7.1.1) to state that authorization should be used for the Poll Endpoint
Fixes #208
> Fixes issue #208 - Poll endpoint should require authorization

- openid-sharedsignals-framework-1_0.md
Reverts openid/sharedsignals#225
> Revert "Issue-224: events_supported field added to .well-known/ssf-configurat…"

- openid-sharedsignals-framework-1_0.md
This is an attempt at some language for recommending the validation of the audience in the stream configuration.
It seems quite vague.... As @FragLegs mentions in the issue, it could be good to be more concrete on what this audience value should be.
Fixes #207
> Adding some language for recommended stream configuration audience validation

- openid-sharedsignals-framework-1_0.md
> Introduce inactivity_timeout

- openid-sharedsignals-framework-1_0.md
This PR adds some examples of wildcard matching behavior for Complex Subjects. It does not change any definitions in the spec - simply gives examples of the definitions in practice.
Closes #197
> Add examples for wildcard matching with Complex Subjects

- openid-sharedsignals-framework-1_0.md
In reference to [Issue 255](https://github.com/openid/sharedsignals/issues/255) marked for v1 Final per the discussion last week in the SSWG Call. 
I added a sub section under Section 4 called "SSF Prescriptive SETs" and an example figure of what a prescriptive SET may look like under Section 5.
Open to feedback on the example. I took the IPSIE action out as defined [here](https://github.com/openid/ipsie/issues/66) and replaced it with a duplicative `session-revoked` event to convey that the transmitter is expecting the action to be taken is to revoke a session even though the SET is referencing the same event. I am all for using an IPSIE profile in there to convey cross standard usage of SSF but wanted to get some feedback from the reviewers. 
I thought Section 4 was a decent place to …
> Generic Language for prescriptive SETs - Issue 255

- .markdownlint.yaml
- openid-caep-1_0.md
- openid-caep-interoperability-profile-1_0.md
- openid-sharedsignals-framework-1_0.md
- working-group-charter.md
Using a markdown linter (https://github.com/DavidAnson/markdownlint/tree/v0.37.4), i cleaned up our markdown files. all has been tested running the `make` command.
I overwrote some of the default linter settings in `.markdownlint.yaml` that didn't align with kramdown-rfc/xml2rfc generators
I cleaned up the markdown for the following files:
- openid-caep-1_0.md
- openid-caep-interoperability-profile-1_0.md
- openid-sharedsignals-framework-1_0.md
- working-group-charter.md
I also opened #264 to update RISC to use md as source of truth rather than xml for easier maintenance
> Fixes Issue #91 - Clean up markdown

- .gitignore
- Makefile
- openid-caep-1_0.md
- openid-risc-1_0.xml
- openid-sharedsignals-framework-1_0.md
We want this round of implementer's draft to become the final v1. We have added a few non-normative changes during the review period for draft 4 (typo fixes and examples) that we would like to have included in that v1. Mike Jones has suggested that we publish a draft 5 and make it part of the current vote instead of trying to restart the process. There is precedent for this action.
> Prepare specs for CAEP draft 5, RISC draft 3, and SSF draft 5
